from Candidates import *

LINKER = {Candidates.EVELIEN_19: "Evelien_19.txt", Candidates.EVI_19: "Evi_19.txt", Candidates.JAMIE_19: "Jamie_19.txt",
          Candidates.MEREL_19: "Merel_19.txt", Candidates.NIELS_19: "Niels_19.txt", Candidates.NIKKIE_19: "Nikkie_19.txt",
          Candidates.RICK_PAUL_19: "Rick_Paul_19.txt", Candidates.ROBERT_19: "Robert_19.txt", Candidates.SARAH_19: "Sarah_19.txt",
          Candidates.SINAN_19: "Sinan_19.txt", Candidates.BELLA_18: "Bella_18.txt", Candidates.EMILIO_18: "Emilio_18.txt",
          Candidates.JAN_18: "Jan_18.txt", Candidates.JEAN_MARC_18: "Jean_Marc_18.txt", Candidates.LOES_18: "Loes_18.txt",
          Candidates.OLCAY_18: "Olcay_18.txt", Candidates.RON_18: "Ron_18.txt", Candidates.RUBEN_18: "Ruben_18.txt",
          Candidates.SIMONE_18: "Simone_18.txt", Candidates.STINE_18: "Stine_18.txt", Candidates.DIEDERIK_17: "Diederik_17.txt",
          Candidates.IMANUELLE_17: "Imanuelle_17.txt", Candidates.JEROEN_17: "Jeroen_17.txt", Candidates.JOCHEM_17: "Jochem_17.txt",
          Candidates.ROOS_17: "Roos_17.txt", Candidates.SANNE_17: "Sanne_17.txt", Candidates.SIGRID_17: "Sigrid_17.txt",
          Candidates.THOMAS_17: "Thomas_17.txt", Candidates.VINCENT_17: "Vincent_17.txt", Candidates.YVONNE_17: "Yvonne_17.txt",
          Candidates.AIREN_16: "Airen_16.txt", Candidates.ANNEMIEKE_16: "Annemieke_16.txt", Candidates.CECILE_16: "Cecile_16.txt",
          Candidates.ELLIE_16: "Ellie_16.txt", Candidates.KLAAS_16: "Klaas_16.txt", Candidates.MARJOLEIN_16: "Marjolein_16.txt",
          Candidates.REMY_16: "Remy_16.txt", Candidates.ROP_16: "Rop_16.txt", Candidates.TAEKE_16: "Taeke_16.txt",
          Candidates.TIM_16: "Tim_16.txt", Candidates.AJOUAD_15: "Ajouad_15.txt", Candidates.CAROLINA_15: "Carolina_15.txt",
          Candidates.CHRIS_15: "Chris_15.txt", Candidates.EVELIEN_15: "Evelien_15.txt", Candidates.MARGRIET_15: "Margriet_15.txt",
          Candidates.MARLIJN_15: "Marlijn_15.txt", Candidates.MARTINE_15: "Martine_15.txt", Candidates.PIETER_15: "Pieter_15.txt",
          Candidates.RIK_15: "Rik_15.txt", Candidates.VIKTOR_15: "Viktor_15.txt", Candidates.AAF_14: "Aaf_14.txt",
          Candidates.DAPHNE_14: "Daphne_14.txt", Candidates.FREEK_14: "Freek_14.txt", Candidates.JAN_WILLEM_14: "Jan_Willem_14.txt",
          Candidates.JENNIFER_14: "Jennifer_14.txt", Candidates.MAURICE_14: "Maurice_14.txt", Candidates.OWEN_14: "Owen_14.txt",
          Candidates.SOFIE_14: "Sofie_14.txt", Candidates.SUSAN_14: "Susan_14.txt", Candidates.TYGO_14: "Tygo_14.txt",
          Candidates.CAROLIEN_13: "Carolien_13.txt", Candidates.DANIEL_13: "Daniel_13.txt", Candidates.EWOUT_13: "Ewout_13.txt",
          Candidates.JANINE_13: "Janine_13.txt", Candidates.JOEP_13: "Joep_13.txt", Candidates.KEES_13: "Kees_13.txt",
          Candidates.PAULIEN_13: "Paulien_13.txt", Candidates.TANIA_13: "Tania_13.txt", Candidates.TIM_13: "Tim_13.txt",
          Candidates.ZARAYDA_13: "Zarayda_13.txt", Candidates.ANNE_MARIE_12: "Anne_Marie_12.txt", Candidates.DIO_12: "Dio_12.txt",
          Candidates.FRITS_12: "Frits_12.txt", Candidates.HADEWYCH_12: "Hadewych_12.txt", Candidates.LIESBETH_12: "Liesbeth_12.txt",
          Candidates.MAARTEN_12: "Maarten_12.txt", Candidates.MARIT_12: "Marit_12.txt", Candidates.MARION_12: "Marion_12.txt",
          Candidates.TIM_12: "Tim_12.txt", Candidates.WILLIAM_12: "William_12.txt", Candidates.ANNA_11: "Anna_11.txt",
          Candidates.ART_11: "Art_11.txt", Candidates.HANNA_11: "Hanna_11.txt", Candidates.HORACE_11: "Horace_11.txt",
          Candidates.JAN_11: "Jan_11.txt", Candidates.KARIN_11: "Karin_11.txt", Candidates.MIRYANNA_11: "Miryanna_11.txt",
          Candidates.PATRICK_11: "Patrick_11.txt", Candidates.PEPIJN_11: "Pepijn_11.txt", Candidates.SOUNDOS_11: "Soundos_11.txt",
          Candidates.ARJEN_10: "Arjen_10.txt", Candidates.BARBARA_10: "Barbara_10.txt", Candidates.ERIK_10: "Erik_10.txt",
          Candidates.FRITS_10: "Frits_10.txt", Candidates.HIND_10: "Hind_10.txt", Candidates.KIM_10: "Kim_10.txt",
          Candidates.LORETTA_10: "Loretta_10.txt", Candidates.MANUEL_10: "Manuel_10.txt", Candidates.SANNE_10: "Sanne_10.txt",
          Candidates.TIM_10: "Tim_10.txt", Candidates.ANNIEK_9: "Anniek_9.txt", Candidates.DENNIS_9: "Dennis_9.txt",
          Candidates.FROUKJE_9: "Froukje_9.txt", Candidates.HANS_9: "Hans_9.txt", Candidates.JON_9: "Jon_9.txt",
          Candidates.PAULA_9: "Paula_9.txt", Candidates.RICK_9: "Rick_9.txt", Candidates.SEBASTIAAN_9: "Sebastiaan_9.txt",
          Candidates.VERA_9: "Vera_9.txt", Candidates.VIVIENNE_9: "Vivienne_9.txt"}